<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<title>Test TomTom</title>
</head>
<body>
<center>
<?php
$sub_dir = "";
$rnd_token = mt_rand(100000000, 999999999);
$date_token = date("Ymd");
if (isset($_GET["itn"])) {
  if (strlen($_GET["itn"]) < 10000) {
    $itn = $_GET["itn"];
    $fname = "tomtom/" .  $date_token . $rnd_token . ".itn";
    file_put_contents($fname, $itn);

    // Need to zip the file
    $cmd = shell_exec("zip -j " . $fname . ".zip " . $fname);

    // Create itinerary xml file
    $xml = "<?xml version='1.0' encoding='utf-8' ?>\n";
    $xml = $xml . "<item>\n";
    $xml = $xml . "<itinerary idstr='OptiMap "
        . $date_token . $rnd_token . "' version='1'>\n";
    $xml = $xml . "<start>Home</start>\n";
    $xml = $xml . "<finish>Home</finish>\n";
    $xml = $xml . "<distance km='0' />\n";
    $xml = $xml . "<title mimetype='text/plain'>"
        . "OptiMap route</title>\n";
    $xml = $xml . "<description mimetype='text/plain'>"
        . "Route generated by OptiMap</description>\n";
    $xml = $xml . "<size>" . strlen($itn) . "</size>\n";
    $xml = $xml . "<download>\n";
    $xml = $xml . "<url location='http://www.gebweb.net/optimap/"
        . $sub_dir . $fname . ".zip' content='main' />\n";
    $xml = $xml . "</download>\n";
    $xml = $xml . "<targetdevice models='all' />\n";
    $xml = $xml . "<price free='true' />\n";
    $xml = $xml . "<supplier>\n";
    $xml = $xml . "<name>gebweb.net</name>\n";
    $xml = $xml . "</supplier>\n";
    $xml = $xml . "</itinerary>\n";
    $xml = $xml . "</item>\n";

    file_put_contents($fname . ".xml", $xml);

    echo "<a href='http://addto.tomtom.com/api/home/v2/content?"
        . "action=install"
        . "&apikey=4db7cb3c-146e-4cd5-ae48-8998a464a4d9"
        . "&uri=http://www.gebweb.net/optimap/" . $sub_dir . $fname
        . ".xml'>";
    echo "<img src='http://addto.tomtom.com/"
        . "api/images/addtotomtom-button.gif' alt='Add-To-TomTom'"
        . "border='0'/></a>\n";
    echo "<a href='http://www.gebweb.net/optimap/" . $sub_dir . $fname
        . "'>Download itinerary file</a>\n";
  } else {
    echo "Itinerary is too large!\n";
  }
}
?>
</center>
</body>
</html>
